#!/usr/bin/perl -w
use strict;
use Bio::SearchIO;
use Bio::Graphics;
use Bio::SeqFeature::Generic;
use Bio::Index::Blast;
use Bio::SearchIO::Writer::TextResultWriter;
use CGI;
use Tie::File;
use File::Basename;
use Digest::MD5 qw(md5 md5_hex md5_base64);
use URI::Escape;
use JSON;
my $cgi = CGI->new;

my $file = uri_unescape($cgi->param('file'));
my $list = uri_unescape($cgi->param('list'));
my $id = uri_unescape($cgi->param('id')); 
my $img_dir = '/export/software/apache/htdocs/';
my $img_url = '/tmpblast/';
my $idx_dir = '/export/software/apache/htdocs/tmpblast/';
my $fname = '';
my $qlist = $cgi->param('qlist');
my $md5;

if($qlist) {
    my $start = $cgi->param('start');
    my $limit = $cgi->param('limit');
    my @querys;
    tie @querys, 'Tie::File', $qlist;
    my $total = scalar @querys;
    print "Content-type: text/plain\n\n";
    print "{total: $total,\nroot: [\n";
    map {
        print to_json({'name' => $_}).",\n";
    } @querys[$start..$start+$limit];
    print "]}";
    exit;
}
if($file) {
    $fname = basename($file);
    $md5 = md5_hex($file);
}
if($list) {
   $fname = basename($list);
   $md5 = md5_hex($list);
}
print STDERR "$md5\n";
my $indexed_file = "$idx_dir/$md5.idx";
my $indexed = -e $indexed_file;

my $index = Bio::Index::Blast->new(-filename => $indexed_file,
                                   -write_flag => 1);
unless ($indexed) {
   print STDERR "Creating .idx\n";
                              #$index->id_parser(\&get_id);
                              # sub get_id {
                              # my $line = shift;
                              #      $line =~ /Query= (\S+)/;
                              ##      print $1;
                              #      $1;
                              #  }
   my $files = [];
   if($list) {
        open IN, "<$list" or die;
        while(<IN>) {
            chomp;
            push(@$files, $_);
        }
    }
    else {
        $files = [$file];
    }
   $index->make_index(@$files);
}

my $fh = $index->get_stream($id);
my $searchio = Bio::SearchIO->new(-noclose => 1,
                                  -format  => 'blast',
                                  -fh      => $fh); 

my $result = $searchio->next_result() or die "No Result.\n";

my $panel = Bio::Graphics::Panel->new(
        -length  => $result->query_length,
         -width   => 600,
         -pad_left   => 10,
         -pad_right  => 10,
      );

my $full_length = Bio::SeqFeature::Generic->new(
         -start   => 1,
         -end           => $result->query_length,
         -display_name  => $result->query_name,
      );

$panel->add_track($full_length,
         -glyph   => 'arrow',
         -tick    => 2,
         -fgcolor => 'black',
         -double  => 1,
         -label   => 1,
      );

my $track = $panel->add_track(
         -glyph   => 'graded_segments',
         -label   => 1,
         -connector  => 'dashed',
         -bgcolor => 'blue',
         -font2color => 'red',
         -sort_order => 'high_score',
         -description => sub {
            my $feature = shift;
            return unless $feature->has_tag('description');
            my ($description) = $feature->each_tag_value('description');
            my $score = $feature->score;
            "$description, score=$score";
            },
      );

while (my $hit = $result->next_hit) {
 ##next unless $hit->significance < 1E-20;
   my $feature = Bio::SeqFeature::Generic->new(
         -display_name  => $hit->name,
         -score         => $hit->raw_score,
         -tag           => {
                  description => $hit->description
                  },
         );
#   print STDERR "$hit->name\n";
   while(my $hsp = $hit->next_hsp ) {
      $feature->add_sub_SeqFeature($hsp,'EXPAND');
   }
   $track->add_feature($feature);
}

my ($url,$map,$mapname)= 
   $panel->image_and_map(-root => $img_dir,
                         -url => $img_url,
                         -link => '#$name',
                         -mapname => "$id");

my $stream = $index->get_stream($id);
#open WH, *STDOUT;
#open (WH, ">", "$file.html");
print "Content-type: text/html\n\n";
#print  "<html>\n<body>\n<pre>";
print "<pre>";

my $last=0;
while (<$stream>) {
   if (/^.?BLAST/) {
      $last++;
      if ($last >1) {last};
   }
   my $line = $_;
   if ($line =~ m/^\>(\S+)/) {
     print  "<a name=$1> $line</a>\n";
   }
   else {print $line;}
   if ($line =~ m/Searching.*done/) {
      print  "</pre>\n"; 
      print  "$map\n";
      print   qq(<img src="$url" usemap="#$mapname">),"\n";
      print  "<pre>\n";
   }
} 
print "</pre>";
#print  "</pre>\n</body>\n</html>\n";

close $stream || die "error\n";
#close WH || die "error\n";


